<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Configurations</span>
        <small>List of site settings that can be configured</small>
    </div>
</nav>

<div class="container p-3">
    <?php foreach($groups as $gprs): ?>
        <div class="row">
            <?php foreach($gprs as $name => $group): ?>
            <div class="col-md-6 pb-3">
                <div class="card card-left-icon">
                    <div class="card-icon bg-primary text-white" style="width:8rem;">
                        <?= $group->icon ?>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><?= hs($group->label) ?></h5>
                        <p class="card-text"><?= hs($group->info) ?></p>
                        <?php if(isset($group->route)): ?>
                            <a href="<?= $this->router->to($group->route[0], $group->route[1], $group->route[2]) ?>">Change settings</a>
                        <?php else: ?>
                            <a href="<?= $this->router->to('adminSiteSettingSingle', ['group'=>$name]) ?>">Change settings</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>