<div class="card">
    <div class="list-group list-group-flush">
        <?php foreach($items as $itm): ?>
            <a href="<?= $this->router->to('adminSiteSettingEdit', ['group'=>$group->name,'item'=>$itm->id]) ?>" class="list-group-item list-group-item-action<?= ($itm->id == $active?' active':'') ?>">
                <div class="d-flex w-100 justify-content-between">
                    <div class="list-group-item-label"><?= hs($itm->name) ?></div>
                </div>
                <small style="display:block">
                    <?php if('' === $itm->value): ?>
                        <em class="text-muted">empty</em>
                    <?php else: ?>
                        <?= hs($itm->value); ?>
                    <?php endif; ?>
                </small>
            </a>
        <?php endforeach; ?>
    </div>
</div>