<?php $can_edit = $this->can_i->update_site_setting; ?>
<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0"><?= hs($group->label) ?> Preferences</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminSiteSettingIndex') ?>">Site Setting</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= hs($group->label) ?></li>
            </ol>
        </nav>
    </div>
    <div class="form-inline">
        <input type="search" class="form-control" placeholder="Search" id="setting-filter">
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-6">
            <div class="card">

                <div class="list-group list-group-flush linkfilter" data-input="#setting-filter">
                    <?php foreach($items as $item): ?>
                        <a href="<?= ($can_edit ? $this->router->to('adminSiteSettingEdit', ['group'=>$group->slug,'item'=>$item->id]) : '#0') ?>" class="list-group-item list-group-item-action" data-text="<?= hs($item->name) ?>">
                            <div class="d-flex w-100 justify-content-between">
                                <div class="list-group-item-label"><?= hs($item->name) ?></div>
                            </div>
                            <small>
                                <?php if('' === $item->value): ?>
                                    <em class="text-muted">empty</em>
                                <?php else: ?>
                                    <code class="text-truncate" style="display:block">
                                        <?= hs($item->value); ?>
                                    </code>
                                <?php endif; ?>
                            </small>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if($saved): ?>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            $.toaster({
                content: 'The setting successfully updated',
                title: 'Success',
                info: 'just now',
                position: 'bottom right'
            })
        });
    </script>
<?php endif; ?>