<?php $can_edit = $this->can_i->update_site_setting; ?>
<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0"><?= hs($group->name) ?> Preferences</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminSetting') ?>">Setting</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= hs($group->name) ?></li>
            </ol>
        </nav>
    </div>
    <div class="form-inline">
        <input type="search" class="form-control" placeholder="Search" id="setting-filter">
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-6">
            <?= $this->partial('site-setting/menu__items', ['items'=>$items, 'active'=>0]) ?>
        </div>
    </div>
</div>

<?php if($saved): ?>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            $.toaster({
                content: 'The setting successfully updated',
                title: 'Success',
                info: 'just now',
                position: 'bottom right'
            })
        });
    </script>
<?php endif; ?>